import './globals.css'
import { Inter, Libre_Caslon_Display, Red_Hat_Display } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

const libre_caslon_display = Libre_Caslon_Display({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-libre_caslon_display' 
})

const red_hat_display = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-red_hat_display'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${libre_caslon_display.variable} ${red_hat_display.variable}`}>{children}</body>
    </html>
  )
}
